{% set version = "25.0.0" %}
{% set sha256 = "27d5387e5f4f2e9b4ccc0ab63c284fbdc565902521fb01dd54d373a504dd853d" %}
{% set galaxy_version = version.split(".")[:2]|join(".") %}

package:
  name: galaxy-tool-util
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/galaxy-tool-util/galaxy_tool_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - galaxy-tool-test=galaxy.tool_util.verify.script:main
    - galaxy-tool-test-case-validation=galaxy.tool_util.parameters.scripts.validate_test_cases:main
    - galaxy-tool-upgrade-advisor=galaxy.tool_util.upgrade.script:main
    - validate-test-format=galaxy.tool_util.validate_test_format:main
    - mulled-build=galaxy.tool_util.deps.mulled.mulled_build:main
    - mulled-build-channel=galaxy.tool_util.deps.mulled.mulled_build_channel:main
    - mulled-search=galaxy.tool_util.deps.mulled.mulled_search:main
    - mulled-build-tool=galaxy.tool_util.deps.mulled.mulled_build_tool:main
    - mulled-build-files=galaxy.tool_util.deps.mulled.mulled_build_files:main
    - mulled-list=galaxy.tool_util.deps.mulled.mulled_list:main
    - mulled-update-singularity-containers=galaxy.tool_util.deps.mulled.mulled_update_singularity_containers:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    # Depend on galaxy-util during build time to avoid packaging galaxy/__init__.py .
    - galaxy-util >={{ galaxy_version }}
  run:
    - python >={{ python_min }}
    - conda-package-streaming
    - galaxy-util >={{ galaxy_version }}
    - lxml
    - markupsafe
    - packaging
    - pydantic >=2
    - pyyaml
    - requests
    - sortedcontainers
    - typing_extensions
    - whoosh

test:
  requires:
    - python {{ python_min }}
  imports:
    - galaxy
    - galaxy.tool_util
    - galaxy.tool_util.biotools
    - galaxy.tool_util.cwl
    - galaxy.tool_util.deps
    - galaxy.tool_util.deps.container_resolvers
    - galaxy.tool_util.deps.mulled
    - galaxy.tool_util.deps.resolvers
    - galaxy.tool_util.linters
    - galaxy.tool_util.locations
    - galaxy.tool_util.parser
    - galaxy.tool_util.toolbox
    - galaxy.tool_util.toolbox.filters
    - galaxy.tool_util.toolbox.lineages
    - galaxy.tool_util.unittest_utils
    - galaxy.tool_util.verify
    - galaxy.tool_util.verify.asserts
  commands:
    - galaxy-tool-test --help
    - galaxy-tool-test-case-validation --help
    # - galaxy-tool-upgrade-advisor --help  # Can be restored after https://github.com/galaxyproject/galaxy/pull/19605
    - validate-test-format --help
    - mulled-build --help
    - mulled-build-channel --help
    - mulled-search --help
    - mulled-search -s bwa
    - mulled-build-tool --help
    - mulled-build-files --help
    - mulled-list --help
    - mulled-update-singularity-containers --help

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: Galaxy Tool and Tool Dependency Utilities
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
